FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
MAINTAINER MYEONGGYULEE <brstar96@espresomedia.com>
RUN apt-get update -y && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update \
 && apt-get install -y curl git unzip vim \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN mkdir /root/.ssh
EXPOSE 22
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN pip3 install numpy pillow scipy scikit-image matplotlib pandas opencv-python ipython pyyaml tensorboardX

# setup openssh
RUN apt-get update
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd

# set password
RUN echo 'root:qwer1234' |chpasswd

#replace sshd_config
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN echo '/usr/sbin/sshd' >> ~/.bashrc
RUN service ssh start

WORKDIR /home
CMD ["/bin/bash"]