# general settings
modelname: pix2pix_v1

# datasets
datasets:
  train:
    train_input_img: /home/datasets/LensflareRemovalDataset/train_input_img/
    train_label_img: /home/datasets/LensflareRemovalDataset/train_label_img/
    train_input_pt: /home/datasets/LensflareRemovalDataset/train_input_img_pt/
    train_label_pt: /home/datasets/LensflareRemovalDataset/train_label_img_pt/
    train_csv: /home/datasets/LensflareRemovalDataset/train_splited.csv
    batch_size: 64
    patch_size: 256
    stride: 128
    direction: a2b # input:a, label:b
    mean: [0.206, 0.218, 0.196]
    std: [0.232, 0.239, 0.231]
    split: train
    flip: true
    rot: true
  val:
    val_path: /home/datasets/LensflareRemovalDataset/
    val_csv: /home/datasets/LensflareRemovalDataset/val_splited.csv
    mean: [0.206, 0.218, 0.196]
    std: [0.232, 0.239, 0.231]
    batch_size: 64
  test:
    test_path: /home/datasets/LensflareRemovalDataset/test_input_img
    test_csv: /home/datasets/LensflareRemovalDataset/test.csv
    mean: [0.214, 0.225, 0.204]
    std: [0.208, 0.216, 0.210]
    batch_size: 64

# network settings
networks:
  which_model: pix2pix_v1
  gpu_ids: 0


# path to save trained model
paths:
  experiment_root: ./experiment
  result_path: ./experiment/image_results

# optimizer
trainer:
  lr: !!float 2e-4
  beta1: 0.5
  beta2: 0.999
  epochs: 300
  workers: 0
  val_step: 1
  resume: False
  resume_path: ~